export const ADD_PRODUCT_TO_CART = "CART_ADD_PRODUCT_TO_CART";
export const DELETE_ITEM = "CART_DELETE_ITEM";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const ADD_SHIPPING = "ADD_SHIPPING";
export const CLEAR_CART = "CLEAR_CART";
